### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by kylefox** [jart/justinetunney.com#1]
Super random, it looks like maybe your blog's font is using the wrong glyph for the 's' — hilarity ensues.

![fcreenfhot](https://cloud.githubusercontent.com/assets/37838/9024088/db5183ea-3877-11e5-8a36-d40d26c67b07.png)

**Comment by jart** [comment]
Working as intended. That's the long s. https://en.wikipedia.org/wiki/Long_s
